version: '3'
services:
    viscoin:
        container_name: viscoin
        restart: always
        build: .
        environment:
            - HTTP_API=:80
            - TCP_API=:9332
            - TCP_NODE=:9333
            - DEBUG=0
        ports:
            - 80:80
            - 9332:9332
            - 9333:9333
        volumes:
            - ./db:/viscoin/db